# audit risk classfication implimentation

In [23]:
#import all the required package
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,precision_score,recall_score,roc_auc_score,f1_score,accuracy_score
from sklearn import model_selection
from sklearn.model_selection import cross_val_score

In [2]:
#import the dataset
input_df=pd.read_csv(r"C:\Users\pavan\Desktop\data_science\audit_risk\audit_risk.csv")

In [3]:
#size of the dataset
print(input_df.shape)

(776, 27)


In [4]:
#check missing value
print(input_df.isna().sum())

Sector_score      0
LOCATION_ID       0
PARA_A            0
Score_A           0
Risk_A            0
PARA_B            0
Score_B           0
Risk_B            0
TOTAL             0
numbers           0
Score_B.1         0
Risk_C            0
Money_Value       1
Score_MV          0
Risk_D            0
District_Loss     0
PROB              0
RiSk_E            0
History           0
Prob              0
Risk_F            0
Score             0
Inherent_Risk     0
CONTROL_RISK      0
Detection_Risk    0
Audit_Risk        0
Risk              0
dtype: int64


In [5]:
#check duplicate value
print(input_df.duplicated().any())

True


In [6]:
#drop duplicate value
print(input_df.drop_duplicates(inplace=True))

None


In [7]:
input_df.loc[input_df['LOCATION_ID']=='LOHARU','LOCATION_ID']=45
input_df.loc[input_df['LOCATION_ID']=='NUH','LOCATION_ID']=46
input_df.loc[input_df['LOCATION_ID']=='SAFIDON','LOCATION_ID']=47

In [8]:
#replace location_id from string to int
input_df['LOCATION_ID']=input_df['LOCATION_ID'].astype(str)
input_df['LOCATION_ID']=input_df['LOCATION_ID'].astype(int)

In [9]:
#since we have na value in money_value column replace it with mean of that row
input_df['Money_Value'].fillna((input_df['Money_Value'].mean()),inplace=True)


In [10]:
#total is just thee total of para_A and para_b
#since the detection_risk has no co relation value we are dropping it.
input_df.drop(columns=['TOTAL','Detection_Risk'],inplace=True)

In [13]:
X=input_df.drop(columns='Risk')
y=input_df['Risk']

In [14]:
#stadadization using standardscalar
sc=StandardScaler()
X1=sc.fit_transform(X)
X1_new=pd.DataFrame(X1)

In [15]:
#splitting train and text data
xtrain,xtest,ytrain,ytest=train_test_split(X1_new,y)

In [16]:
#impliment logistic regression
from sklearn.linear_model import LogisticRegression
lg=LogisticRegression()
model1=lg.fit(xtrain,ytrain)
ypred1=model1.predict(xtest)

In [25]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state=7)
scoring = 'accuracy'
acc_logi = cross_val_score(estimator = lg, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_logi.mean()

0.9754990925589837

In [43]:
#model evaluation
acc=accuracy_score(ytest,ypred1)
prec=precision_score(ytest,ypred1)
rec=recall_score(ytest,ypred1)
f1=f1_score(ytest,ypred1)
roc=roc_auc_score(ytest,ypred1)
results= pd.DataFrame([['Logistic Regression',acc, acc_logi.mean(),prec,rec, f1,roc]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.984293            0.975499   0.986667  0.973684   

   F1 Score       ROC  
0  0.980132  0.982494

In [29]:
#prediction for train data using logistic regression
ypred2=model1.predict(xtrain)
np.mean(ytrain==ypred2)

0.9825174825174825

In [27]:
#confusion matrix from Logistic regression test data
confusion_matrix(ytest,ypred1)

array([[114,   1],
       [  2,  74]], dtype=int64)

In [30]:
#confusion matrix from Logistic regression train data
confusion_matrix(ytrain,ypred2)

array([[341,   3],
       [  7, 221]], dtype=int64)

In [32]:
#implimenting knn 
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
model2=knn.fit(xtrain,ytrain)
ypred3=model2.predict(xtest)

In [33]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state=7)
scoring = 'accuracy'

acc_knn = cross_val_score(estimator = knn, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_knn.mean()

C:\Users\pavan\Anaconda5\envs\plot\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


0.9545372050816695

In [44]:
#model evaluation
acc_knn=accuracy_score(ytest,ypred3)
prec_knn=precision_score(ytest,ypred3)
rec_knn=recall_score(ytest,ypred3)
f1_knn=f1_score(ytest,ypred3)
roc_knn=roc_auc_score(ytest,ypred3)
results_knn= pd.DataFrame([['KNN',acc_knn, acc_knn.mean(),prec_knn,rec_knn, f1_knn,roc_knn]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results=results.append(results_knn,ignore_index=True)
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.984293            0.975499   0.986667  0.973684   
1                  KNN  0.984293            0.984293   0.986667  0.973684   

   F1 Score       ROC  
0  0.980132  0.982494  
1  0.980132  0.982494

In [45]:
#prediction for train data using KNN
ypred4=model2.predict(xtrain)
np.mean(ytrain==ypred4)

0.9702797202797203

In [46]:
#confusion matrix from KNN test data
confusion_matrix(ytest,ypred3)

array([[114,   1],
       [  2,  74]], dtype=int64)

In [47]:
#confusion matrix from KNN train data
confusion_matrix(ytrain,ypred4)

array([[339,   5],
       [ 12, 216]], dtype=int64)

In [53]:
from sklearn.tree import DecisionTreeClassifier
dc=DecisionTreeClassifier(criterion='gini')
model3=dc.fit(xtrain,ytrain)
ypred5=model3.predict(xtest)

1.0

In [51]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state=7)
scoring = 'accuracy'

acc_dc = cross_val_score(estimator = dc, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_dc.mean()

C:\Users\pavan\Anaconda5\envs\plot\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


0.9982456140350877

In [50]:
#model evaluation
acc_dc=accuracy_score(ytest,ypred5)
prec_dc=precision_score(ytest,ypred5)
rec_dc=recall_score(ytest,ypred5)
f1_dc=f1_score(ytest,ypred5)
roc_dc=roc_auc_score(ytest,ypred5)
results_dc= pd.DataFrame([['DecisionTree',acc_dc, acc_dc.mean(),prec_dc,rec_dc, f1_dc,roc_dc]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results=results.append(results_dc,ignore_index=True)
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.984293            0.975499   0.986667  0.973684   
1                  KNN  0.984293            0.984293   0.986667  0.973684   
2         DecisionTree  1.000000            1.000000   1.000000  1.000000   

   F1 Score       ROC  
0  0.980132  0.982494  
1  0.980132  0.982494  
2  1.000000  1.000000

In [52]:
#prediction for train data using decision tree
ypred6=model2.predict(xtrain)
np.mean(ytrain==ypred6)

0.9702797202797203

In [54]:
#confusion matrix from decision tree test data
confusion_matrix(ytest,ypred5)

array([[115,   0],
       [  0,  76]], dtype=int64)

In [56]:
#confusion matrix from decision tree train data
confusion_matrix(ytrain,ypred6)

array([[339,   5],
       [ 12, 216]], dtype=int64)

In [68]:
#implimenting random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,criterion='gini')
model4=rf.fit(xtrain,ytrain)
ypred7=model4.predict(xtest)

In [69]:
#cross validation
kfold = model_selection.KFold(n_splits=10, random_state=7)
scoring = 'accuracy'

acc_rf = cross_val_score(estimator = rf, X = xtrain, y = ytrain, cv = kfold,scoring=scoring)
acc_rf.mean()

C:\Users\pavan\Anaconda5\envs\plot\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


0.9982456140350877

In [70]:
#model evaluation
acc_rf=accuracy_score(ytest,ypred7)
prec_rf=precision_score(ytest,ypred7)
rec_rf=recall_score(ytest,ypred7)
f1_rf=f1_score(ytest,ypred7)
roc_rf=roc_auc_score(ytest,ypred7)
results_rf= pd.DataFrame([['Random forest',acc_rf, acc_rf.mean(),prec_rf,rec_rf, f1_rf,roc_rf]],
               columns = ['Model', 'Accuracy','Cross Val Accuracy', 'Precision', 'Recall', 'F1 Score','ROC'])
results=results.append(results_rf,ignore_index=True)
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.984293            0.975499   0.986667  0.973684   
1                  KNN  0.984293            0.984293   0.986667  0.973684   
2         DecisionTree  1.000000            1.000000   1.000000  1.000000   
3        Random forest  1.000000            1.000000   1.000000  1.000000   
4        Random forest  1.000000            1.000000   1.000000  1.000000   

   F1 Score       ROC  
0  0.980132  0.982494  
1  0.980132  0.982494  
2  1.000000  1.000000  
3  1.000000  1.000000  
4  1.000000  1.000000

In [66]:
#predict train data using randomforest
ypred8=model4.predict(xtrain)
accuracy_score(ytrain,ypred8)

1.0

In [64]:
#confusion matrix from randomforest test data
confusion_matrix(ytest,pred7)

array([[115,   0],
       [  0,  76]], dtype=int64)

In [65]:
#confusion matrix from randomforest train data
confusion_matrix(ytrain,ypred8)

array([[344,   0],
       [  0, 228]], dtype=int64)

In [72]:
#from the above model building random forest was best model based all accuracy
#score precision ,recall and also it performed good on both test and train data
results

Model  Accuracy  Cross Val Accuracy  Precision    Recall  \
0  Logistic Regression  0.984293            0.975499   0.986667  0.973684   
1                  KNN  0.984293            0.984293   0.986667  0.973684   
2         DecisionTree  1.000000            1.000000   1.000000  1.000000   
3        Random forest  1.000000            1.000000   1.000000  1.000000   

   F1 Score       ROC  
0  0.980132  0.982494  
1  0.980132  0.982494  
2  1.000000  1.000000  
3  1.000000  1.000000